---
# Consul role defaults
consul_version: "1.17.1"
consul_config_dir: "/etc/consul.d"
consul_data_dir: "/opt/consul/data"
hashicorp_install_dir: "/opt/hashicorp"
datacenter: "dc1"
enable_tls: true
tls_dir: "/opt/hashicorp/tls"
enable_acl: true
consul_acl_default_policy: "deny"
consul_encrypt_key: ""
consul_bootstrap_expect: 1
consul_retry_join: []
consul_ui_enabled: true
consul_log_level: "INFO"
